OTAWA_APP_PATH = "/home/acac/otawa/otawa-xdd/cmake-build-debug/xengine/pipe_analyses_test"
TACLE_PATH = "/home/acac/tacle-bench"
OTAWA_PROPS = [
    "otawa::xengine::XSTEPS_OUTPUT_PATH=./xstep.out", 
    "otawa::xengine::XENGINE_CONFIG_OUTPUT_PATH=./xengine.out", 
    "otawa::CACHE_CONFIG_PATH=/home/acac/otawa/otawa-xdd/arch/complex_cache.xml",
    "otawa::MEMORY_PATH=/home/acac/otawa/otawa-xdd/arch/complex_mem.xml",
    "otawa::hard::PROCESSOR_ID=otawa::omach::Complex"
    ]
OTAWA_LOG_LEVEL = "deps"
