root_path = "/home/acac/tacle-bench/"
[[benchsets]]
name = "kernel"
path_from_root = "bench/kernel/"
benchs = [
            # name = name of bench, which will be generated as task name
            # exec = path from the directory of benchset
            { name = "binarysearch", exec = "binarysearch/binarysearch.elf", entry_point = "binarysearch_main"},
            { name = "complex_updates", exec = "complex_updates/complex_updates.elf", entry_point = "complex_updates_main"},
            { name = "deg2rad", exec = "deg2rad/deg2rad.elf", entry_point = "deg2rad_main"},
            { name = "fir2dim", exec = "fir2dim/fir2dim.elf", entry_point = "fir2dim_main"},
            { name = "jfdctint", exec = "jfdctint/jfdctint.elf", entry_point = "jfdctint_main"},
            { name = "md5", exec = "md5/md5.elf", entry_point = "md5_main"},
            { name = "quicksort", exec = "quicksort/quicksort.elf", entry_point = "quicksort_main"},
            { name = "st", exec = "st/st.elf", entry_point = "st_main"},
            { name = "bitcount", exec = "bitcount/bitcount.elf", entry_point = "bitcount_main"},
            { name = "cosf", exec = "cosf/cosf.elf", entry_point = "cosf_main"},
            { name = "fac", exec = "fac/fac.elf", entry_point = "fac_main"},
            { name = "iir", exec = "iir/iir.elf", entry_point = "iir_main"},
            { name = "lms", exec = "lms/lms.elf", entry_point = "lms_main"},
            { name = "minver", exec = "minver/minver.elf", entry_point = "minver_main"},
            { name = "rad2deg", exec = "rad2deg/rad2deg.elf", entry_point = "rad2deg_main"},
            { name = "bitonic", exec = "bitonic/bitonic.elf", entry_point = "bitonic_main"},
            { name = "countnegative", exec = "countnegative/countnegative.elf", entry_point = "countnegative_main"},
            { name = "fft", exec = "fft/fft.elf", entry_point = "fft_main"},
            { name = "insertsort", exec = "insertsort/insertsort.elf", entry_point = "insertsort_main"},
            { name = "ludcmp", exec = "ludcmp/ludcmp.elf", entry_point = "ludcmp_main"},
            { name = "pm", exec = "pm/pm.elf", entry_point = "pm_main"},
            { name = "recursion", exec = "recursion/recursion.elf", entry_point = "recursion_main"},
            { name = "bsort", exec = "bsort/bsort.elf", entry_point = "bsort_main"},
            { name = "cubic", exec = "cubic/cubic.elf", entry_point = "cubic_main"},
            { name = "filterbank", exec = "filterbank/filterbank.elf", entry_point = "filterbank_main"},
            { name = "isqrt", exec = "isqrt/isqrt.elf", entry_point = "isqrt_main"},
            { name = "matrix1", exec = "matrix1/matrix1.elf", entry_point = "matrix1_main"},
            { name = "prime", exec = "prime/prime.elf", entry_point = "prime_main"},
            { name = "sha", exec = "sha/sha.elf", entry_point = "sha_main"},
        ]